import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import styled from "styled-components";

import List from "./list";
import Form from "./message";
import Map from "./map";
import Footer from "@/components/Footer";
import { Margin, MarginNFx } from "@/styles/globalSC";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main className={styles.main}>
        <H1>GET IN TOUCH</H1>
        <Section>
          <Wrap>
            <List />
            {/* <Form /> */}
          </Wrap>
        </Section>
        <Section>
          <Map />
        </Section>
        <Footer />
      </Main>
    </>
  );
}

const Main = styled.main`
  padding-top: 70px;
  width: 100vw;
`;

const Section = styled.section`
  width: 100vw;
`;

const Wrap = styled.div`
  width: 100%;
  max-width: 1220px;
  margin: 0px auto;

  display: flex;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
`;

const H1 = styled.h1`
  width: 100%;
  max-width: 1220px;
  margin: 0px auto;
  padding: 10px;

  font-family: Montserrat;
  color: hsla(35, 35%, 35%, 1);
  font-size: clamp(20px, 7vw, 50px);
`;
